FROM node:20

# Set up working directory
WORKDIR /app/slicer

# Copy entire slicer app including links.csv
COPY . .

# Install dependencies
RUN npm install

# Recreate symlinks based on links.csv
RUN bash -c '\
    while IFS=, read -r link target; do \
    echo "Restoring $link -> $target"; \
    rm -f "$link"; \
    mkdir -p "$(dirname "$link")"; \
    ln -s "$target" "$link"; \
    done < links.csv \
    '