FROM node:20

WORKDIR /app/slicer
# Copy only the necessary subfolders and files to avoid the symlink issue
COPY apps apps
COPY bin bin
COPY docs docs
COPY mods mods
COPY sample sample
COPY src src
COPY web web
COPY app-el.js app-el.js
COPY app.js app.js
COPY package.json package.json

# Now explicitly copy all that into apps/grid
RUN mkdir -p apps/grid && \
    cp -r bin conf data docs logs mods sample src tmp web app-el.js app.js package.json package-lock.json apps/grid/

RUN npm install
