services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8283:8283"
    environment:
      ENV: production
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8283
    restart: unless-stopped

  frontend:
    build:
      context: ./slicer
      dockerfile: Dockerfile.frontend
    ports:
      - "5174:5174"
    working_dir: /app/slicer
    command: npm run dev -- --host 0.0.0.0 --port 5174
    restart: unless-stopped
