services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8282:8282"
    environment:
      ENV: production
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8282
    restart: unless-stopped

  frontend:
    build:
      context: ./slicer
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    working_dir: /app/slicer
    command: npm run dev -- --host 0.0.0.0 --port 5173
    restart: unless-stopped
