version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8282:8282"
    environment:
      - ENV=production
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./slicer
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    working_dir: /app/slicer
    command: npm run prod -- --host 0.0.0.0 --port 5173
